source 'https://rubygems.org'

gem 'builder', '~> 3.2.0'
gem 'middleman', '~> 3.3.0'
gem 'middleman-autoprefixer', git: 'git@github.com:kaishin/middleman-autoprefixer.git'
gem 'middleman-blog'
gem 'middleman-deploy'
gem 'middleman-imageoptim', '~> 0.1.4'
gem 'middleman-livereload', '~> 3.3.0'
gem 'middleman-dotenv', '~> 1.0'
gem 'middleman-minify-html'
gem 'middleman-neat', '~> 0.0.4'
gem 'rake', '~> 10.1.0'
gem 'redcarpet'
